services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/app
            - ./docker/nginx/log:/var/log/nginx
        depends_on:
            - php-fpm
            - db
            - redis

    php-fpm:
        build:
            context: docker/php-fpm
        env_file: ./.env
        command: bash -c 'entrypoint'
        volumes:
            - ./:/app
            - ./docker/php-fpm/entrypoint.bash:/usr/local/bin/entrypoint
            - ./docker/php-fpm/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - db
            - redis

    db:
        build:
            context: docker/mysql
        environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        ports:
        - "3307:3306"
        command: --mysql-native-password=ON
        volumes:
            - db_data:/var/lib/mysql

    redis:
        build:
            context: docker/redis
        ports:
        - "6379:6379"
        volumes:
        - redis_data:/data
    minio:
        image: minio/minio:latest
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server --console-address ":9001" /data
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data

volumes:
  db_data:
  redis_data:
  minio_data:
